<script type="text/javascript">
    Ext.onReady(function(){
        var viewport = new Ext.Viewport({
            layout: 'border',
            id: 'movieview',
            renderTo: document.body,
            items: [
                {
                    region: "north",
                    tbar: [{
                            xtype: 'toolbar',
                            items: [{
                                    text: 'Sytem',
                                    iconCls: 'icon-table',
                                    menu: [{ text: 'Menu 1' },{ text: 'Menu 1'}]
                                }, '-', {
                                    text: 'Category',
                                    iconCls: 'icon-chart',
                                    menu: [{ text: 'Menu 3'}, { text: 'Menu 4'}]
                                }, '-', {
                                    text: 'Report',
                                    iconCls: 'icon-chart',
                                    menu: [{ text: 'Menu 3'}, { text: 'Menu 4'}]
                                }]
                        }]
                },{
                    region: 'west',
                    border: false,
                    split: true,
                    collapsible: true,
                    collapseMode: 'mini',
                    title: 'Menu',
                    width: 250,
                    minSize: 250
                },{
                    title: 'Center Panel',
                    region: 'center',
                    border: false
                }
            ]
        }); 
    }); //Ext.onReady
</script>