<script type="text/javascript">
    Ext.QuickTips.init();

    var loginForm = { xtype: 'form',
        id: 'login-form',
        bodyStyle: 'padding:15px;background:transparent',
        border: false,
        items: [
            { xtype: 'textfield', id: 'username', fieldLabel: '<?php echo $this->translate('Tên đăng nhập'); ?>',
                allowBlank: false, minLength: 3, maxLength: 32, width: 200
            },
            { xtype: 'textfield', id: 'password', fieldLabel: '<?php echo $this->translate('Mật khẩu'); ?>', inputType: 'password',
                allowBlank: false, minLength: 3, maxLength: 32, width: 200
            }
        ],
        buttons: [{
                text: 'Login',
                handler: function() {
                    Ext.getCmp('login-form').getForm().submit(
                    {
                        waitMsg: '<?php echo $this->translate('Đang xữ lý...'); ?>',
                        success: function(form, action){
                            window.location.href = '<?php echo $this->baseUrl() . '/admin' ?>'
                        },
                        failure: function(form, action){
                            Ext.Msg.show({
                                title:'<?php echo $this->translate('Cảnh Báo'); ?>',
                                msg: '<?php echo $this->translate('Tên đăng nhập hoặc mật khẩu không hợp lệ. Xin vui lòng thử lại.'); ?>',
                                icon: Ext.MessageBox.ERROR,
                                buttons: Ext.MessageBox.OK
                            });
                        }
                    }
                );
                }
            }]
    }

    Ext.onReady(function() {

        win = new Ext.Window({
            applyTo: 'login-win',
            layout: 'form',
            title: '<?php echo $this->translate('Đăng Nhập'); ?>',
            draggable: false,
            resizable: false,
            width: 350,
            autoHeight: true,
            closable: false,
            errorReader: new Ext.data.JsonReader(),
            items: [loginForm]

        });

        win.show();
    });


</script>

<div id="login-win">
</div>