<script type="text/javascript">
    Ext.QuickTips.init();

    var loginForm = { xtype: 'form',
        id: 'login-form',
        bodyStyle: 'padding:15px;background:transparent',
        border: false,
        items: [
            { xtype: 'textfield', id: 'username', fieldLabel: '<?php echo $this->translate('Username');?>',
                allowBlank: false, minLength: 3, maxLength: 32, width: 200
            },
            { xtype: 'textfield', id: 'password', fieldLabel: '<?php echo $this->translate('Password');?>', inputType: 'password',
                allowBlank: false, minLength: 3, maxLength: 32, width: 200,
                minLengthText: '<?php echo $this->translate('Password must be at least 6 characters long');?>'
            }
        ],
        buttons: [{
                text: 'Login',
                handler: function() {
                    Ext.getCmp('login-form').getForm().submit(
                    {
                        waitMsg: '<?php echo $this->translate('Submitting your data...');?>',
                        success: function(form, action){
                            window.location.href = 'http://local.qlbh/admin'
                        },
                        failure: function(form, action){
                            alert('Fail');
                        }
                    }
                );
                }
            }]
    }

    Ext.onReady(function() {

        win = new Ext.Window({
            applyTo: 'login-win',
            layout: 'form',
            title: 'Login Form',
            draggable: false,
            resizable: false,
            width: 350,
            autoHeight: true,
            closable: false,
            errorReader: new Ext.data.JsonReader(),
            items: [loginForm]

        });

        win.show();
    });


</script>

<div id="login-win">
</div>