<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php  
echo $this->headTitle();  
echo $this->headMeta();
echo $this->headLink(); 
echo $this->headStyle();
?>
</head>
<body>
        <div id="container">
            <div id="main">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>

<?php
echo $this->headScript(); 
?>
</body>
</html>
