<div class="midnav">
	<div class="iconviewtype">
		<a href="#" title="List view"><img src="/images/ico_viewThumb.gif" /></a><a href="#" title="Thumbnail view"><img src="/images/ico_viewList.gif" /></a>
	</div>
	<div class="itemcategories">
	<?php
	for($i=0; $i<8; $i++)
	{
	    ?>
	    <div class="cont01">
			<div class="cont01im">
				<a href="#"><img src="/images/sample.jpg" /></a>
			</div>
			<div class="cont01txt"><a href="#">Girl</a></div>
		</div>
	    <?php
	} 
	?>
	</div>
	<div class="paging"><a href="#">1</a><a href="#">2</a><a href="#">3</a><a href="#">4</a></div>
</div>