<?php
/**
 * Classic pagination style
 * 
 * @preview  ‹ First  < 1 2 3 >  Last ›
 */
?>

<div class="pagination" style="width:100%">
	<div style="float:right;width:70%; text-align:right">
		<?php if ($this->first_page): ?>
			<a href="<?php echo $this->url(array('page' => 1)); ?>">&lsaquo;&nbsp;First</a> |
		<?php endif ?>
		<?php if ($this->previous_page): ?>
	    	&laquo; <a href="<?php echo $this->url(array('page' => $this->previous_page)); ?>"></a> |
	  	<?php endif ?>
		
	  	<?php for ($i = 1; $i <= $this->total_pages; $i++): ?>
			<?php if ($i == $this->current_page): ?>
				<strong><?php echo $i ?></strong>
			<?php else: ?>
				<a href="<?php echo $this->url(array('page' => $i));?>"><strong><?php echo $i?></strong></a>
    		<?php endif ?>
		<?php endfor ?>
		
		<?php if ($this->next_page): ?>
			<a href="<?php echo $this->url(array('page' => $this->next_page)); ?>">&gt;</a>
		<?php endif ?>
  
		<?php if ($this->last_page): ?>
			<a href="<?php echo $this->url(array('page' => $this->last_page)); ?>">Last&nbsp;&rsaquo;</a>
  		<?php endif ?>
	</div>
</div>