<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php $this->headTitle()->setSeparator(" - ");
        echo $this->headTitle('Admin Control Panel') ?>
        <?php $this->headScript()->appendFile($this->baseUrl() . '/js/extjs3/ext-base.js') ?>
        <?php $this->headScript()->appendFile($this->baseUrl() . '/js/extjs3/ext-all.js') ?>
        
        <!--Config global-->
        <?php $this->headScript()->appendFile($this->baseUrl() . '/js/qlbh/app/config/global.js') ?>
        
        <!--DM Nganh Hang-->
        <?php $this->headScript()->appendFile($this->baseUrl() . '/js/qlbh/app/view/dm.nganhhang/DMNganhHang.js') ?>
        
        <?php echo $this->headScript(); ?>
        <?php $this->headLink()->prependStylesheet($this->baseUrl() . '/js/extjs3/resources/css/ext-all.css'); ?>
        <?php echo $this->headLink(); ?>
    </head>
    <body>
        <?php echo $this->layout()->content ?>
    </body>
</html>	